### ISSUE TITLE
Add 64-bit monotonically increasing state counter

### ISSUE THREAD

**Issue by secworks** [tillitis/tkey-random-generator#16]
In the current implementation, the context contains a 32 bit counter (ctr). The counter is used to (1) evolve the state and (2) track when it is time to reseed the state. Using the counter for two separate things is bad design. And more importantly, if the entropy source is broken, when reseeding (and the counter is being reset to zero), we would create a loop of random data with the length given by the reseed parameter.

I suggest to:
(1) Rename the counter to "reseed_ctr" and only use it to track when to reseed.
(2) Add a second counter "state_ctr", but make that counter 64 bit and never reset it. The counter is mixed into word 14 and 15 of the state. The state counter could be implemented as two separate uint32_t.

**Comment by secworks** [comment]
PR https://github.com/tillitis/tkey-random-generator/pull/19 adds a separate 64 bit counter that is randomly initialized, monotonically increasing and never reset.

**Comment by dehanj** [comment]
#19 Merged.
