### ISSUE TITLE
Add support for USS

### ISSUE THREAD

**Issue by dehanj** [tillitis/tkey-random-generator#6]
To lower the risk of someone uses your TKey for signing, the USS could be used.

**Comment by dehanj** [comment]
Already included while loading the app.

**Comment by secworks** [comment]
Basically add a "-uss" to allow the user to include a USS when loading the TKey app, to have it being included when calculating the CDI.

**Comment by mchack-work** [comment]
Especially important since CDI is not just used for signing here.
